services:
web:
build: 
context: /home/usuario/Docker/Caronte/proyectos/pbase/deploy
dockerfile: proyectos/pbase/deploy/Dockerfile/pbase/Dockerfile
#args: 
#- USUARIO=oliver
container_name: ctpbase
environment:
- USUARIO=dangelo