version: '3.8'

services:
  web:
    build:
      context: /home/dangelo/Escritorio/HLC/Docker/Caronte/proyectos/pbase/deploy
      dockerfile: Docker/Dockerfiles/sgbd/Dockerfile
      #args: 
      #- USUARIO=oliver
    container_name: ctpbase
    environment:
      - USUARIO=dangelo
